name: "CI"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: robherley/go-test-action@v0

  tag:
    name: tag
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: write
    outputs:
      next: ${{ steps.tag.outputs.NEXT_TAG }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: biohackerellie/auto-git-tag@v1
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branch: 'main' # Optional, default is 'release'
          dry_run: false # Optional, default is false
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.tag.outputs.NEXT_TAG }}"
          prerelease: false
          files: |
            LICENSE
            README.md

  deploy:
    needs: tag
    uses: mhornbacher/zoom-to-control4/.github/workflows/deploy.yml@main
    with:
      release-tag: "${{ needs.tag.outputs.next }}"
