on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: robherley/go-test-action@v0

  tag:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: valitydev/action-autotag@v1
